### PR TITLE
Toggle

### PR DESCRIPTION
**Pull request by wraithgar**
This is #7 rebased to master and updated to have the optional second css paramter.

thanks to @fyockm for the original PR and his patience while we got to this.

### CODE REVIEW

**Comment by fyockm** [comment]
LGTM :+1: 

thanks for updating @wraithgar

**Comment by lukekarrys** [comment]
+1

**Comment by wraithgar** [comment]
Waiting on npm access to publish.

**Comment by wraithgar** [comment]
Published as `v1.5.0`

**Pull request merged**
